In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

toolkit = pd.read_csv(r"C:\Users\dell\Downloads\RawData-main\RawData-main\Superstore.csv",encoding="latin1")
toolkit

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261.9600,2,41.9136
1,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731.9400,3,219.5820
2,12-06-2018,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,14.6200,2,6.8714
3,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957.5775,5,-383.0310
4,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,22.3680,2,2.5164
...,...,...,...,...,...,...,...,...,...,...,...
9989,21-01-2016,Tom Boeckenhauer,Consumer,Miami,Florida,South,Furniture,Furnishings,25.2480,3,4.1028
9990,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Furniture,Furnishings,91.9600,2,15.6332
9991,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Technology,Phones,258.5760,2,19.3932
9992,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Office Supplies,Paper,29.6000,4,13.3200
9993,04-05-2019,Chris Cortes,Consumer,Westminster,California,West,Office Supplies,Appliances,243.1600,2,72.9480

In [5]:
toolkit.head(5)

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261.9600,2,41.9136
1,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731.9400,3,219.5820
2,12-06-2018,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,14.6200,2,6.8714
3,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957.5775,5,-383.0310
4,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,22.3680,2,2.5164

In [6]:
toolkit.tail(5)

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
9989,21-01-2016,Tom Boeckenhauer,Consumer,Miami,Florida,South,Furniture,Furnishings,25.248,3,4.1028
9990,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Furniture,Furnishings,91.960,2,15.6332
9991,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Technology,Phones,258.576,2,19.3932
9992,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Office Supplies,Paper,29.600,4,13.3200
9993,04-05-2019,Chris Cortes,Consumer,Westminster,California,West,Office Supplies,Appliances,243.160,2,72.9480

In [7]:
toolkit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Date     9994 non-null   object
 1   Customer Name  9994 non-null   object
 2   Segment        9994 non-null   object
 3   City           9994 non-null   object
 4   State          9994 non-null   object
 5   Region         9994 non-null   object
 6   Category       9994 non-null   object
 7   Sub-Category   9994 non-null   object
 8   Sales          9994 non-null   float64
 9   Quantity       9994 non-null   int64
 10  Profit         9994 non-null   float64
dtypes: float64(2), int64(1), object(8)
memory usage: 859.0+ KB

In [8]:
toolkit.describe()

              Sales     Quantity       Profit
count   9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574    28.656896
std      623.245101     2.225110   234.260108
min        0.444000     1.000000 -6599.978000
25%       17.280000     2.000000     1.728750
50%       54.490000     3.000000     8.666500
75%      209.940000     5.000000    29.364000
max    22638.480000    14.000000  8399.976000

In [9]:
toolkit.isnull().sum()

Order Date       0
Customer Name    0
Segment          0
City             0
State            0
Region           0
Category         0
Sub-Category     0
Sales            0
Quantity         0
Profit           0
dtype: int64

In [10]:
toolkit["Sales"].dtype

dtype('float64')

In [11]:
toolkit["Sales"] = toolkit["Sales"].astype(int)

In [12]:
toolkit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Date     9994 non-null   object
 1   Customer Name  9994 non-null   object
 2   Segment        9994 non-null   object
 3   City           9994 non-null   object
 4   State          9994 non-null   object
 5   Region         9994 non-null   object
 6   Category       9994 non-null   object
 7   Sub-Category   9994 non-null   object
 8   Sales          9994 non-null   int64
 9   Quantity       9994 non-null   int64
 10  Profit         9994 non-null   float64
dtypes: float64(1), int64(2), object(8)
memory usage: 859.0+ KB

In [13]:
toolkit["Region"]

0       South
1       South
2        West
3       South
4       South
        ...
9989    South
9990     West
9991     West
9992     West
9993     West
Name: Region, Length: 9994, dtype: object

In [14]:
print(toolkit.to_string())

      Order Date           Customer Name      Segment               City                 State   Region         Category Sub-Category  Sales  Quantity     Profit
0     08-11-2018             Claire Gute     Consumer          Henderson              Kentucky    South        Furniture    Bookcases    261         2    41.9136
1     08-11-2018             Claire Gute     Consumer          Henderson              Kentucky    South        Furniture       Chairs    731         3   219.5820
2     12-06-2018         Darrin Van Huff    Corporate        Los Angeles            California     West  Office Supplies       Labels     14         2     6.8714
3     11-10-2017          Sean O'Donnell     Consumer    Fort Lauderdale               Florida    South        Furniture       Tables    957         5  -383.0310
4     11-10-2017          Sean O'Donnell     Consumer    Fort Lauderdale               Florida    South  Office Supplies      Storage     22         2     2.5164
5     09-06-2016         Brosina Hoffman     Consumer        Los Angeles            California     West        Furniture  Furnishings     48         7    14.1694
6     09-06-2016         Brosina Hoffman     Consumer        Los Angeles            California     West  Office Supplies          Art      7         4     1.9656
7     09-06-2016         Brosina Hoffman     Consumer        Los Angeles            California     West       Technology       Phones    907         6    90.7152
8     09-06-2016         Brosina Hoffman     Consumer        Los Angeles            California     West  Office Supplies      Binders     18         3     5.7825
9     09-06-2016         Brosina Hoffman     Consumer        Los Angeles            California     West  Office Supplies   Appliances    114         5    34.4700
10    09-06-2016         Brosina Hoffman     Consumer        Los Angeles            California     West        Furniture       Tables   1706         9    85.3092
11    09-06-2016         Brosina Hoffman     Consumer        Los Angeles            California     West       Technology       Phones    911         4    68.3568
12    15-04-2019            Andrew Allen     Consumer            Concord        North Carolina    South  Office Supplies        Paper     15         3     5.4432
13    05-12-2018            Irene Maddox     Consumer            Seattle            Washington     West  Office Supplies      Binders    407         3   132.5922
14    22-11-2017           Harold Pawlan  Home Office         Fort Worth                 Texas  Central  Office Supplies   Appliances     68         5  -123.8580
15    22-11-2017           Harold Pawlan  Home Office         Fort Worth                 Texas  Central  Office Supplies      Binders      2         3    -3.8160
16    11-11-2016               Pete Kriz     Consumer            Madison             Wisconsin  Central  Office Supplies      Storage    665         6    13.3176
17    13-05-2016         Alejandro Grove     Consumer        West Jordan                  Utah     West  Office Supplies      Storage     55         2     9.9900
18    27-08-2016      Zuschuss Donatelli     Consumer      San Francisco            California     West  Office Supplies          Art      8         2     2.4824
19    27-08-2016      Zuschuss Donatelli     Consumer      San Francisco            California     West       Technology       Phones    213         3    16.0110
20    27-08-2016      Zuschuss Donatelli     Consumer      San Francisco            California     West  Office Supplies      Binders     22         4     7.3840
21    09-12-2018               Ken Black    Corporate            Fremont              Nebraska  Central  Office Supplies          Art     19         7     5.0596
22    09-12-2018               Ken Black    Corporate            Fremont              Nebraska  Central  Office Supplies   Appliances     60         7    15.6884
23    16-07-2019         Sandra Flanagan     Consumer       Philadelphia          Pennsylvania     East        Furniture       Chairs     71         2    -1.0196
24    25-09-2017             Emily Burns     Consumer               Orem                  Utah     West        Furniture       Tables   1044         3   240.2649
25    16-01-2018           Eric Hoffmann     Consumer        Los Angeles            California     West  Office Supplies      Binders     11         2     4.2224
26    16-01-2018           Eric Hoffmann     Consumer        Los Angeles            California     West       Technology  Accessories     90         3    11.7741
27    17-09-2017         Tracy Blumstein     Consumer       Philadelphia          Pennsylvania     East        Furniture    Bookcases   3083         7 -1665.0522
28    17-09-2017         Tracy Blumstein     Consumer       Philadelphia          Pennsylvania     East  Office Supplies      Binders      9         2    -7.0532
29    17-09-2017         Tracy Blumstein     Consumer       Philadelphia          Pennsylvania     East        Furniture  Furnishings    124         3    15.5250
30    17-09-2017         Tracy Blumstein     Consumer       Philadelphia          Pennsylvania     East  Office Supplies    Envelopes      3         2     1.1016
31    17-09-2017         Tracy Blumstein     Consumer       Philadelphia          Pennsylvania     East  Office Supplies          Art     86         6     9.7092
32    17-09-2017         Tracy Blumstein     Consumer       Philadelphia          Pennsylvania     East  Office Supplies      Binders      6         6    -5.7150
33    17-09-2017         Tracy Blumstein     Consumer       Philadelphia          Pennsylvania     East  Office Supplies          Art     15         2     3.5460
34    19-10-2019            Matt Abelman  Home Office            Houston                 Texas  Central  Office Supplies        Paper     29         3     9.9468
35    08-12-2018               Gene Hale    Corporate         Richardson                 Texas  Central       Technology       Phones   1097         7   123.4737
36    08-12-2018               Gene Hale    Corporate         Richardson                 Texas  Central        Furniture  Furnishings    190         5  -147.9630
37    27-12-2017            Steve Nguyen  Home Office            Houston                 Texas  Central  Office Supplies    Envelopes    113         9    35.4150
38    27-12-2017            Steve Nguyen  Home Office            Houston                 Texas  Central        Furniture    Bookcases    532         3   -46.9764
39    27-12-2017            Steve Nguyen  Home Office            Houston                 Texas  Central        Furniture       Chairs    212         3   -15.1470
40    27-12-2017            Steve Nguyen  Home Office            Houston                 Texas  Central       Technology       Phones    371         4    41.7564
41    10-09-2019          Linda Cazamias    Corporate         Naperville              Illinois  Central       Technology       Phones    147         4    16.5564
42    17-07-2018            Ruben Ausman    Corporate        Los Angeles            California     West  Office Supplies      Storage     77         2     3.8940
43    19-09-2019              Erin Smith    Corporate          Melbourne               Florida    South  Office Supplies      Storage     95         2     9.5616
44    11-03-2018           Odella Nelson    Corporate              Eagan             Minnesota  Central       Technology  Accessories     45         2    19.7714
45    11-03-2018           Odella Nelson    Corporate              Eagan             Minnesota  Central  Office Supplies      Binders     17         2     8.2062
46    20-10-2016       Patrick O'Donnell     Consumer           Westland              Michigan  Central  Office Supplies      Storage    211         4     8.4784
47    20-06-2018          Lena Hernandez     Consumer              Dover              Delaware     East       Technology  Accessories     45         3     4.9500
48    20-06-2018          Lena Hernandez     Consumer              Dover              Delaware     East       Technology       Phones     21         2     6.1040
49    18-04-2017           Darren Powers     Consumer         New Albany               Indiana  Central  Office Supplies      Binders     38         6    17.9634
50    18-04-2017           Darren Powers     Consumer         New Albany               Indiana  Central  Office Supplies       Labels     75         6    35.3346
51    18-04-2017           Darren Powers     Consumer         New Albany               Indiana  Central        Furniture  Furnishings      6         2     2.9568
52    18-04-2017           Darren Powers     Consumer         New Albany               Indiana  Central        Furniture       Chairs     89         1    17.0981
53    11-12-2018          Janet Molinari    Corporate      New York City              New York     East  Office Supplies    Fasteners     15         7     6.2566
54    11-12-2018          Janet Molinari    Corporate      New York City              New York     East       Technology       Phones   1029         5   298.6855
55    17-06-2018         Ted Butterfield     Consumer               Troy              New York     East  Office Supplies      Storage    208         6    52.1400
56    17-06-2018         Ted Butterfield     Consumer               Troy              New York     East  Office Supplies        Paper     32         5    15.5520
57    17-06-2018         Ted Butterfield     Consumer               Troy              New York     East        Furniture       Chairs    319         5     7.0980
58    17-06-2018         Ted Butterfield     Consumer               Troy              New York     East  Office Supplies        Paper     14         2     6.9888
59    17-06-2018         Ted Butterfield     Consumer               Troy              New York     East       Technology  Accessories     30         2     3.3000
60    17-06-2018         Ted Butterfield     Consumer               Troy              New York     East  Office Supplies      Binders     48         4    16.3620
61    17-06-2018         Ted Butterfield     Consumer               Troy              New York     East  Office Supplies          Art      1         1     0.8400
62    24-11-2017            Kunst Miller     Consumer        Los Angeles            California     West       Technology  Accessories     13         2     6.1512
63    24-11-2017            Kunst Miller     Consumer        Los Angeles            California     West  Office Supplies      Binders     25         6     9.3612
64    24-11-2017            Kunst Miller     Consumer        Los Angeles            California     West  Office Supplies        Paper    146         3    68.9631
65    24-11-2017            Kunst Miller     Consumer        Los Angeles            California     West        Furniture  Furnishings     79         4    22.3328
66    30-04-2017          Paul Stevenson  Home Office            Chicago              Illinois  Central        Furniture       Chairs    213         5   -15.2225
67    05-12-2016           Brendan Sweed    Corporate            Gilbert               Arizona     West  Office Supplies          Art   1113         8   111.3024
68    05-12-2016           Brendan Sweed    Corporate            Gilbert               Arizona     West       Technology       Phones    167         4    62.9880
69    04-06-2018           Karen Daniels     Consumer        Springfield              Virginia    South  Office Supplies        Paper     75         2    35.6636
70    18-09-2018       Henry MacAllister     Consumer      New York City              New York     East  Office Supplies      Binders      4         1     1.7310
71    14-09-2019         Tracy Blumstein     Consumer            Jackson              Michigan  Central  Office Supplies        Paper     19         3     8.7630
72    26-04-2017              Joel Eaton     Consumer            Memphis             Tennessee    South        Furniture       Chairs    831         8  -114.3912
73    26-04-2017              Joel Eaton     Consumer            Memphis             Tennessee    South        Furniture  Furnishings     97         2     1.2130
74    26-04-2017              Joel Eaton     Consumer            Memphis             Tennessee    South  Office Supplies      Storage     72         1   -18.1960
75    09-12-2019             Ken Brennan    Corporate            Houston                 Texas  Central  Office Supplies      Binders      1         3    -1.9344
76    09-12-2019             Ken Brennan    Corporate            Houston                 Texas  Central        Furniture  Furnishings      9         3    -5.8248
77    09-12-2019             Ken Brennan    Corporate            Houston                 Texas  Central  Office Supplies      Storage     27         3     2.7240
78    26-11-2016              Joel Eaton     Consumer            Houston                 Texas  Central        Furniture  Furnishings     19         5   -14.4750
79    12-06-2018      Stewart Carmichael    Corporate            Decatur               Alabama    South  Office Supplies   Appliances    208         1    56.2032
80    12-06-2018      Stewart Carmichael    Corporate            Decatur               Alabama    South  Office Supplies      Binders     16         3     8.0352
81    12-10-2016            Duane Noonan     Consumer      San Francisco            California     West  Office Supplies          Art     14         5     4.1720
82    12-10-2016            Duane Noonan     Consumer      San Francisco            California     West  Office Supplies      Storage     21         1     6.2031
83    03-09-2017         Julie Creighton    Corporate             Durham        North Carolina    South  Office Supplies    Envelopes    200         7    62.8075
84    13-11-2019      Christopher Schild  Home Office            Chicago              Illinois  Central  Office Supplies      Storage    230         3   -48.9549
85    28-05-2019       Patrick O'Donnell     Consumer           Columbia        South Carolina    South        Furniture       Chairs    301         2    33.2156
86    26-10-2019           Paul Gonzalez     Consumer          Rochester             Minnesota  Central       Technology  Accessories     19         1     6.7966
87    26-10-2019           Paul Gonzalez     Consumer          Rochester             Minnesota  Central  Office Supplies       Labels      6         2     2.9568
88    05-04-2018            Gary Mitchum  Home Office            Houston                 Texas  Central  Office Supplies      Storage    158         7    13.8572
89    17-09-2018                Jim Sink    Corporate        Los Angeles            California     West  Office Supplies          Art     20         3     6.6330
90    17-09-2018                Jim Sink    Corporate        Los Angeles            California     West       Technology       Phones     73         2     8.2782
91    17-09-2018                Jim Sink    Corporate        Los Angeles            California     West  Office Supplies        Paper      6         1     3.1104
92    31-01-2017              Karl Braun     Consumer        Minneapolis             Minnesota  Central  Office Supplies        Paper     12         2     6.2208
93    31-01-2017              Karl Braun     Consumer        Minneapolis             Minnesota  Central        Furniture  Furnishings     53         3    16.5354
94    31-01-2017              Karl Braun     Consumer        Minneapolis             Minnesota  Central  Office Supplies      Binders     32         2    16.1504
95    06-11-2019            Roger Barcio  Home Office           Portland                Oregon     West  Office Supplies      Binders      5         1    -3.7880
96    09-11-2019          Parhena Norris  Home Office      New York City              New York     East        Furniture  Furnishings     96         7    40.5426
97    17-06-2019        Katherine Ducich     Consumer      San Francisco            California     West  Office Supplies      Binders     51         3    17.9592
98    06-09-2018       Elpida Rittenbach    Corporate         Saint Paul             Minnesota  Central  Office Supplies   Appliances     77         6    22.5852
99    29-08-2018            Rick Bensley  Home Office            Chicago              Illinois  Central  Office Supplies        Paper     64         7    22.6184
100   29-08-2018            Rick Bensley  Home Office            Chicago              Illinois  Central       Technology  Accessories     95         3   -10.7973
101   29-08-2018            Rick Bensley  Home Office            Chicago              Illinois  Central  Office Supplies      Binders      1         3    -3.0396
102   01-12-2018           Gary Zandusky     Consumer          Rochester             Minnesota  Central  Office Supplies        Paper     23         4    11.7208
103   13-11-2017           Lena Cacioppo     Consumer             Aurora              Colorado     West       Technology  Accessories    238         6   -26.8758
104   13-11-2017           Lena Cacioppo     Consumer             Aurora              Colorado     West        Furniture  Furnishings    102         3    -3.8385
105   13-11-2017           Lena Cacioppo     Consumer             Aurora              Colorado     West  Office Supplies      Binders     36         3   -25.8174
106   23-11-2019            Janet Martin     Consumer          Charlotte        North Carolina    South       Technology  Accessories     74         8    17.6016
107   23-11-2019            Janet Martin     Consumer          Charlotte        North Carolina    South       Technology       Phones     27         1     2.0994
108   23-11-2019            Janet Martin     Consumer          Charlotte        North Carolina    South  Office Supplies          Art      3         1     1.0738
109   15-10-2017          Pete Armstrong  Home Office        Orland Park              Illinois  Central       Technology  Accessories    339         5    67.9920
110   25-12-2019           Cynthia Voltz    Corporate      New York City              New York     East        Furniture  Furnishings     41         2    10.9096
111   03-11-2018             Clay Ludtke     Consumer          Urbandale                  Iowa  Central  Office Supplies          Art     75         2    22.7880
112   03-11-2018             Clay Ludtke     Consumer          Urbandale                  Iowa  Central  Office Supplies      Binders     27         6    13.3476
113   25-08-2016              Ryan Crowe     Consumer           Columbus                  Ohio     East  Office Supplies    Fasteners     40        14    14.5348
114   25-08-2016              Ryan Crowe     Consumer           Columbus                  Ohio     East  Office Supplies    Envelopes      4         2     1.6520
115   25-08-2016              Ryan Crowe     Consumer           Columbus                  Ohio     East  Office Supplies        Paper     23         3     7.4925
116   25-08-2016              Ryan Crowe     Consumer           Columbus                  Ohio     East  Office Supplies    Envelopes    130         6    44.0316
117   02-03-2017               Dave Kipp     Consumer            Seattle            Washington     West        Furniture       Tables    787         3   165.3813
118   05-04-2017            Greg Guthrie    Corporate            Bristol             Tennessee    South  Office Supplies      Binders    157         1  -115.7156
119   12-06-2018       Steven Cartwright     Consumer         Wilmington              Delaware     East        Furniture  Furnishings     47         3    18.3456
120   12-06-2018       Steven Cartwright     Consumer         Wilmington              Delaware     East  Office Supplies      Binders     30         4    13.8780
121   12-06-2018       Steven Cartwright     Consumer         Wilmington              Delaware     East  Office Supplies      Storage    226         6    63.4368

In [15]:
toolkit[["Sales","Region","Category"]]

      Sales Region         Category
0       261  South        Furniture
1       731  South        Furniture
2        14   West  Office Supplies
3       957  South        Furniture
4        22  South  Office Supplies
...     ...    ...              ...
9989     25  South        Furniture
9990     91   West        Furniture
9991    258   West       Technology
9992     29   West  Office Supplies
9993    243   West  Office Supplies

[9994 rows x 3 columns]

In [16]:
toolkit["Country"] = "India"
toolkit

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit,Country
0,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261,2,41.9136,India
1,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731,3,219.5820,India
2,12-06-2018,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,14,2,6.8714,India
3,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957,5,-383.0310,India
4,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,22,2,2.5164,India
...,...,...,...,...,...,...,...,...,...,...,...,...
9989,21-01-2016,Tom Boeckenhauer,Consumer,Miami,Florida,South,Furniture,Furnishings,25,3,4.1028,India
9990,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Furniture,Furnishings,91,2,15.6332,India
9991,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Technology,Phones,258,2,19.3932,India
9992,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Office Supplies,Paper,29,4,13.3200,India
9993,04-05-2019,Chris Cortes,Consumer,Westminster,California,West,Office Supplies,Appliances,243,2,72.9480,India

In [17]:
toolkit.drop(columns="Country",inplace=True)
toolkit

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261,2,41.9136
1,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731,3,219.5820
2,12-06-2018,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,14,2,6.8714
3,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957,5,-383.0310
4,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,22,2,2.5164
...,...,...,...,...,...,...,...,...,...,...,...
9989,21-01-2016,Tom Boeckenhauer,Consumer,Miami,Florida,South,Furniture,Furnishings,25,3,4.1028
9990,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Furniture,Furnishings,91,2,15.6332
9991,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Technology,Phones,258,2,19.3932
9992,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Office Supplies,Paper,29,4,13.3200
9993,04-05-2019,Chris Cortes,Consumer,Westminster,California,West,Office Supplies,Appliances,243,2,72.9480

In [18]:
toolkit.rename(columns={"Customer Name" : "Name"})

,Order Date,Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261,2,41.9136
1,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731,3,219.5820
2,12-06-2018,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,14,2,6.8714
3,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957,5,-383.0310
4,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,22,2,2.5164
...,...,...,...,...,...,...,...,...,...,...,...
9989,21-01-2016,Tom Boeckenhauer,Consumer,Miami,Florida,South,Furniture,Furnishings,25,3,4.1028
9990,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Furniture,Furnishings,91,2,15.6332
9991,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Technology,Phones,258,2,19.3932
9992,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Office Supplies,Paper,29,4,13.3200
9993,04-05-2019,Chris Cortes,Consumer,Westminster,California,West,Office Supplies,Appliances,243,2,72.9480

In [19]:
toolkit.drop_duplicates("Customer Name")

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261,2,41.9136
2,12-06-2018,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,14,2,6.8714
3,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957,5,-383.0310
5,09-06-2016,Brosina Hoffman,Consumer,Los Angeles,California,West,Furniture,Furnishings,48,7,14.1694
12,15-04-2019,Andrew Allen,Consumer,Concord,North Carolina,South,Office Supplies,Paper,15,3,5.4432
...,...,...,...,...,...,...,...,...,...,...,...
8666,30-12-2018,Carl Jackson,Corporate,Philadelphia,Pennsylvania,East,Office Supplies,Art,16,5,1.6520
9209,11-12-2019,Roy Skaria,Home Office,Burlington,Iowa,Central,Office Supplies,Envelopes,7,1,3.4944
9399,11-11-2018,Sung Chung,Consumer,Arlington Heights,Illinois,Central,Office Supplies,Art,14,6,1.2348
9441,29-12-2016,Ricardo Emerson,Consumer,Kent,Ohio,East,Office Supplies,Appliances,48,5,6.0450
9558,03-05-2018,Susan MacKendrick,Consumer,Newark,Ohio,East,Technology,Accessories,132,5,34.7865

In [20]:
toolkit[toolkit["Region"]=="West"]

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
2,12-06-2018,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,14,2,6.8714
5,09-06-2016,Brosina Hoffman,Consumer,Los Angeles,California,West,Furniture,Furnishings,48,7,14.1694
6,09-06-2016,Brosina Hoffman,Consumer,Los Angeles,California,West,Office Supplies,Art,7,4,1.9656
7,09-06-2016,Brosina Hoffman,Consumer,Los Angeles,California,West,Technology,Phones,907,6,90.7152
8,09-06-2016,Brosina Hoffman,Consumer,Los Angeles,California,West,Office Supplies,Binders,18,3,5.7825
...,...,...,...,...,...,...,...,...,...,...,...
9986,29-09-2018,Maris LaWare,Consumer,Los Angeles,California,West,Technology,Accessories,36,1,15.2208
9990,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Furniture,Furnishings,91,2,15.6332
9991,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Technology,Phones,258,2,19.3932
9992,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Office Supplies,Paper,29,4,13.3200
9993,04-05-2019,Chris Cortes,Consumer,Westminster,California,West,Office Supplies,Appliances,243,2,72.9480

In [21]:
toolkit[(toolkit["Profit"]>2000) & (toolkit["Category"]=="Technology")]

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
1085,01-03-2018,Karen Daniels,Consumer,Yonkers,New York,East,Technology,Machines,4899,7,2400.9657
2623,22-10-2019,Tom Ashbrook,Home Office,New York City,New York,East,Technology,Copiers,11199,4,3919.9888
4190,17-11-2019,Hunter Lopez,Consumer,Newark,Delaware,East,Technology,Copiers,10499,3,5039.9856
4277,16-04-2018,Bill Shonely,Corporate,Lakewood,New Jersey,East,Technology,Machines,9099,7,2365.9818
6626,14-12-2016,Tom Boeckenhauer,Consumer,New York City,New York,East,Technology,Machines,6999,4,2239.9872
6826,02-10-2018,Tamara Chand,Corporate,Lafayette,Indiana,Central,Technology,Copiers,17499,5,8399.9760
7666,04-10-2018,Daniel Raglin,Home Office,Providence,Rhode Island,East,Technology,Copiers,5399,9,2591.9568
8153,23-03-2019,Raymond Buch,Consumer,Seattle,Washington,West,Technology,Copiers,13999,4,6719.9808
8204,08-11-2017,Keith Dawkins,Corporate,New York City,New York,East,Technology,Machines,4643,4,2229.0240
8488,02-02-2018,Sanjit Engle,Consumer,Arlington,Virginia,South,Technology,Machines,8749,5,2799.9840
8990,24-12-2017,Harry Marie,Corporate,Springfield,Missouri,Central,Technology,Copiers,4899,7,2302.9671

In [22]:
toolkit.nunique()

Order Date       1236
Customer Name     793
Segment             3
City              531
State              49
Region              4
Category            3
Sub-Category       17
Sales            1155
Quantity           14
Profit           7287
dtype: int64

In [23]:
toolkit.columns

Index(['Order Date', 'Customer Name', 'Segment', 'City', 'State', 'Region',
       'Category', 'Sub-Category', 'Sales', 'Quantity', 'Profit'],
      dtype='object')

In [24]:
toolkit.sort_values("Profit",ascending=False)

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
6826,02-10-2018,Tamara Chand,Corporate,Lafayette,Indiana,Central,Technology,Copiers,17499,5,8399.9760
8153,23-03-2019,Raymond Buch,Consumer,Seattle,Washington,West,Technology,Copiers,13999,4,6719.9808
4190,17-11-2019,Hunter Lopez,Consumer,Newark,Delaware,East,Technology,Copiers,10499,3,5039.9856
9039,17-12-2018,Adrian Barton,Consumer,Detroit,Michigan,Central,Office Supplies,Binders,9892,13,4946.3700
4098,23-09-2016,Sanjit Chand,Consumer,Minneapolis,Minnesota,Central,Office Supplies,Binders,9449,5,4630.4755
...,...,...,...,...,...,...,...,...,...,...,...
4991,07-12-2019,Henry Goldwyn,Corporate,Chicago,Illinois,Central,Office Supplies,Binders,1889,5,-2929.4845
3011,17-04-2019,Sharelle Roach,Home Office,Louisville,Colorado,West,Technology,Machines,2549,5,-3399.9800
9774,26-07-2016,Luke Foster,Consumer,San Antonio,Texas,Central,Office Supplies,Binders,2177,8,-3701.8928
683,04-11-2019,Grant Thornton,Corporate,Burlington,North Carolina,South,Technology,Machines,7999,4,-3839.9904
7772,25-11-2018,Cindy Stewart,Consumer,Lancaster,Ohio,East,Technology,Machines,4499,5,-6599.9780

In [25]:
toolkit.iloc[0:4,0:6]

   Order Date    Customer Name    Segment             City       State Region
0  08-11-2018      Claire Gute   Consumer        Henderson    Kentucky  South
1  08-11-2018      Claire Gute   Consumer        Henderson    Kentucky  South
2  12-06-2018  Darrin Van Huff  Corporate      Los Angeles  California   West
3  11-10-2017   Sean O'Donnell   Consumer  Fort Lauderdale     Florida  South

In [26]:
toolkit.loc[0:5]

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261,2,41.9136
1,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731,3,219.5820
2,12-06-2018,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,14,2,6.8714
3,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957,5,-383.0310
4,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,22,2,2.5164
5,09-06-2016,Brosina Hoffman,Consumer,Los Angeles,California,West,Furniture,Furnishings,48,7,14.1694

In [27]:
def view(Sales):
    return Sales+1000

toolkit["Sales"] = toolkit["Sales"].map(view)

In [28]:
root = toolkit["Quantity"].transform (lambda x:x+10)
root

0       12
1       13
2       12
3       15
4       12
        ..
9989    13
9990    12
9991    12
9992    14
9993    12
Name: Quantity, Length: 9994, dtype: int64

In [29]:
toolkit.where(toolkit["Region"]=="West",other="Not Found")

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
1,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
2,12-06-2018,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,1014,2,6.8714
3,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
4,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
...,...,...,...,...,...,...,...,...,...,...,...
9989,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
9990,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Furniture,Furnishings,1091,2,15.6332
9991,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Technology,Phones,1258,2,19.3932
9992,26-02-2019,Dave Brooks,Consumer,Costa Mesa,California,West,Office Supplies,Paper,1029,4,13.32
9993,04-05-2019,Chris Cortes,Consumer,Westminster,California,West,Office Supplies,Appliances,1243,2,72.948

In [30]:
toolkit.groupby(toolkit["Profit"]>4000).max()

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
Profit,,,,,,,,,,,
False,31-12-2018,Zuschuss Donatelli,Home Office,Yuma,Wyoming,West,Technology,Tables,23638,14,3919.9888
True,23-09-2016,Tamara Chand,Corporate,Seattle,Washington,West,Technology,Copiers,18499,13,8399.9760

In [31]:
toolkit.where((toolkit["Category"]=="Furniture") & (toolkit["Region"]=="South"),other="Not Found")

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,1261,2,41.9136
1,08-11-2018,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,1731,3,219.582
2,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
3,11-10-2017,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,1957,5,-383.031
4,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
...,...,...,...,...,...,...,...,...,...,...,...
9989,21-01-2016,Tom Boeckenhauer,Consumer,Miami,Florida,South,Furniture,Furnishings,1025,3,4.1028
9990,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
9991,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
9992,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found
9993,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found,Not Found

In [32]:
toolkit.nsmallest(4,"Sales")

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
2106,26-09-2016,Henry Goldwyn,Corporate,Mesquite,Texas,Central,Office Supplies,Binders,1000,1,-1.4016
2761,12-10-2019,Neil Knudson,Home Office,San Francisco,California,West,Technology,Accessories,1000,1,0.4356
4101,19-06-2019,Zuschuss Carroll,Consumer,Houston,Texas,Central,Office Supplies,Appliances,1000,1,-1.1100
4711,31-03-2016,Jas O'Carroll,Consumer,Philadelphia,Pennsylvania,East,Office Supplies,Binders,1000,1,-0.5964

In [33]:
toolkit.nlargest(4,"Profit")

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
6826,02-10-2018,Tamara Chand,Corporate,Lafayette,Indiana,Central,Technology,Copiers,18499,5,8399.9760
8153,23-03-2019,Raymond Buch,Consumer,Seattle,Washington,West,Technology,Copiers,14999,4,6719.9808
4190,17-11-2019,Hunter Lopez,Consumer,Newark,Delaware,East,Technology,Copiers,11499,3,5039.9856
9039,17-12-2018,Adrian Barton,Consumer,Detroit,Michigan,Central,Office Supplies,Binders,10892,13,4946.3700

In [34]:
toolkit.query("Profit>2000 and Region=='South'")

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
509,16-03-2017,Christopher Martinez,Consumer,Atlanta,Georgia,South,Office Supplies,Binders,7354,5,3177.475
8488,02-02-2018,Sanjit Engle,Consumer,Arlington,Virginia,South,Technology,Machines,9749,5,2799.984

In [35]:
toolkit[["Customer Name","Profit","Sales"]].head(21).style.highlight_max(color="blue")

In [36]:
top_city = toolkit.sort_values(by="Sales", ascending=False).head(5)
top_city

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
2697,18-03-2016,Sean Miller,Home Office,Jacksonville,Florida,South,Technology,Machines,23638,6,-1811.0784
6826,02-10-2018,Tamara Chand,Corporate,Lafayette,Indiana,Central,Technology,Copiers,18499,5,8399.9760
8153,23-03-2019,Raymond Buch,Consumer,Seattle,Washington,West,Technology,Copiers,14999,4,6719.9808
2623,22-10-2019,Tom Ashbrook,Home Office,New York City,New York,East,Technology,Copiers,12199,4,3919.9888
4190,17-11-2019,Hunter Lopez,Consumer,Newark,Delaware,East,Technology,Copiers,11499,3,5039.9856

In [37]:
fig = px.line(top_city,x="City",y="Profit",title="Profit Trend by City",template="plotly_dark")
fig.show()

In [38]:
Top_5_customer_name = toolkit.sort_values(by="Sales",ascending=False).head(5)
Top_5_customer_name

,Order Date,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
2697,18-03-2016,Sean Miller,Home Office,Jacksonville,Florida,South,Technology,Machines,23638,6,-1811.0784
6826,02-10-2018,Tamara Chand,Corporate,Lafayette,Indiana,Central,Technology,Copiers,18499,5,8399.9760
8153,23-03-2019,Raymond Buch,Consumer,Seattle,Washington,West,Technology,Copiers,14999,4,6719.9808
2623,22-10-2019,Tom Ashbrook,Home Office,New York City,New York,East,Technology,Copiers,12199,4,3919.9888
4190,17-11-2019,Hunter Lopez,Consumer,Newark,Delaware,East,Technology,Copiers,11499,3,5039.9856

In [44]:
fig = px.pie(
    toolkit,
    names="Region",
    values="Sales",
    title="Sales Distribution by Region",
    template="plotly_white",
    color="Sales"
)
fig.update_traces(
hole=0.55, textinfo="percent+label",
 marker=dict(line=dict(color='black', width=2)),
 hovertemplate="<b>%{label}</b><br>Sales: %{value}<br>Share: %{percent}"
)
fig.show()

In [45]:
fig = px.bar(Top_5_customer_name,x="Customer Name",y="Sales",color="Sales",text="Sales",template="plotly_white",title="Top 5 Customers by Sales")
fig.show()

In [46]:
fig = px.scatter(toolkit,x="Category",y="Sales",color="Sales",template="plotly_dark",title="Sales Distribution by Category")
fig.show()

In [47]:
fig= px.sunburst(toolkit,path=["Segment"],values="Profit",color="Profit",template="plotly_dark",title="Profit Distribution by Segment")
fig.show()

In [48]:
top_5_city_sale = toolkit.sort_values(by="Sales",ascending=False).head(5)
top_5_city_sale
fig = px.funnel(top_5_city_sale,x="State",y="Sales",color="Sales",title="Top 5 States by Sales")
fig.update_traces(marker_line_width=2)
fig.update_layout(title_x=0.1)
fig.show()